import { createUser, setUserStatus } from "@/actions/admin";
import { PageHeader } from "@/components/admin/page-header";
import { SubmitButton } from "@/components/forms/submit-button";
import { requirePermission } from "@/lib/auth/session";
import { db } from "@/lib/db";

const input = "rounded-lg border border-border-strong bg-surface px-3 py-2 outline-none focus:border-brand-primary focus:ring-2 focus:ring-brand-primary/20";
export default async function UsersPage() {
  await requirePermission("users.read"); const [users, roles] = await Promise.all([db.user.findMany({ include: { roles: { include: { role: true } } }, orderBy: { createdAt: "desc" } }), db.role.findMany({ orderBy: { name: "asc" } })]);
  return <><PageHeader title="Usuários" description="Contas, perfis e situação de acesso." /><details className="mb-6 rounded-2xl border border-border bg-surface p-5"><summary className="cursor-pointer font-bold text-brand-primary-hover">Adicionar usuário</summary><form action={createUser} className="mt-5 grid gap-3 md:grid-cols-2"><input className={input} name="name" placeholder="Nome" required/><input className={input} name="email" placeholder="E-mail" required type="email"/><input className={input} minLength={10} name="password" placeholder="Senha inicial (10+ caracteres)" required type="password"/><select className={input} name="roleId" required><option value="">Selecione o perfil</option>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select><div><SubmitButton>Criar usuário</SubmitButton></div></form></details><div className="grid gap-4">{users.map((user) => <article className="flex flex-col justify-between gap-4 rounded-2xl border border-border bg-surface p-5 sm:flex-row sm:items-center" key={user.id}><div><h2 className="font-bold">{user.name}</h2><p className="text-sm text-text-muted">{user.email} · {user.roles.map(({ role }) => role.name).join(", ")}</p></div><form action={setUserStatus} className="flex gap-2"><input name="id" type="hidden" value={user.id}/><select className={input} defaultValue={user.status} name="status"><option value="ACTIVE">Ativo</option><option value="INACTIVE">Inativo</option><option value="INVITED">Convidado</option></select><button className="rounded-lg border border-border-strong px-3 py-2 font-semibold text-brand-primary-hover transition hover:border-brand-primary">Salvar</button></form></article>)}</div></>;
}
