import Link from "next/link";
import { PageHeader } from "@/components/admin/page-header";
import { requirePermission } from "@/lib/auth/session";
import { db } from "@/lib/db";

export default async function ContactsPage({ searchParams }: { searchParams: Promise<{ status?: string; q?: string }> }) {
  await requirePermission("contacts.read"); const params = await searchParams;
  const leads = await db.contactLead.findMany({ where: { status: params.status && params.status !== "ALL" ? params.status as never : undefined, OR: params.q ? [{ name: { contains: params.q, mode: "insensitive" } }, { email: { contains: params.q, mode: "insensitive" } }, { company: { contains: params.q, mode: "insensitive" } }] : undefined }, orderBy: { createdAt: "desc" }, take: 100 });
  return <><PageHeader title="Contatos" description="Oportunidades recebidas pelo formulário público." /><form className="mb-5 flex flex-col gap-3 rounded-2xl bg-surface p-4 sm:flex-row"><input className="flex-1 rounded-lg border border-border-strong px-3 py-2 outline-none focus:border-brand-primary focus:ring-2 focus:ring-brand-primary/20" defaultValue={params.q} name="q" placeholder="Buscar nome, e-mail ou empresa" /><select className="rounded-lg border border-border-strong px-3 py-2 outline-none focus:border-brand-primary focus:ring-2 focus:ring-brand-primary/20" defaultValue={params.status || "ALL"} name="status"><option value="ALL">Todos</option><option value="NEW">Novos</option><option value="IN_PROGRESS">Em andamento</option><option value="WON">Ganhos</option><option value="LOST">Perdidos</option></select><button className="rounded-lg bg-brand-primary px-5 py-2 font-semibold text-text-primary transition hover:bg-brand-primary-hover hover:text-text-inverse">Filtrar</button></form><div className="overflow-x-auto rounded-2xl border border-border bg-surface"><table className="w-full min-w-3xl text-left text-sm"><thead className="bg-background-secondary text-text-secondary"><tr><th className="p-4">Contato</th><th className="p-4">Empresa</th><th className="p-4">Status</th><th className="p-4">Recebido</th><th className="p-4"></th></tr></thead><tbody className="divide-y divide-border">{leads.map((lead) => <tr key={lead.id}><td className="p-4"><strong>{lead.name}</strong><br/><span className="text-text-muted">{lead.email}</span></td><td className="p-4">{lead.company || "—"}</td><td className="p-4">{lead.status}</td><td className="p-4">{lead.createdAt.toLocaleDateString("pt-BR")}</td><td className="p-4"><Link className="font-semibold text-brand-primary-hover" href={`/admin/contatos/${lead.id}`}>Abrir</Link></td></tr>)}</tbody></table>{!leads.length && <p className="p-10 text-center text-text-muted">Nenhum contato encontrado.</p>}</div></>;
}
